## 1. Tải dữ liệu

In [ ]:
!wget --no-check-certificate \
    https://gist.githubusercontent.com/khacanh/4c4662fa226db87a4664dfc2f70bc63e/raw/5d8a1d890c73a1e92e6898137db28f3dc0676975/kieu.txt \
    -O ./kieu.txt

--2023-03-26 03:41:05--  https://gist.githubusercontent.com/khacanh/4c4662fa226db87a4664dfc2f70bc63e/raw/5d8a1d890c73a1e92e6898137db28f3dc0676975/kieu.txt
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 135832 (133K) [text/plain]
Saving to: ‘./kieu.txt’

./kieu.txt          100%[===================>] 132.65K  --.-KB/s    in 0.002s  

2023-03-26 03:41:05 (53.2 MB/s) - ‘./kieu.txt’ saved [135832/135832]



Load các dòng thơ

In [ ]:
corpus = []
f = open("kieu.txt", "r")
for line in f:
  corpus.append(line)

In [ ]:
len(corpus)

3254

In [ ]:
corpus = corpus[:500]

Kiểm tra các dòng thơ

In [ ]:
corpus

['Trăm năm trong cõi người ta,\n',
 'Chữ tài chữ mệnh khéo là ghét nhau.\n',
 'Trải qua một cuộc bể dâu,\n',
 'Những điều trông thấy mà đau đớn lòng.\n',
 'Lạ gì bỉ sắc tư phong,\n',
 'Trời xanh quen thói má hồng đánh ghen.\n',
 'Cảo thơm lần giỞ trước đèn,\n',
 'Phong tình có lục còn truyền sử xanh.\n',
 'Rằng năm Gia Tĩnh triều Minh,\n',
 'Bốn phương phẳng lặng, hai kinh vững vàng.\n',
 'Có nhà viên ngoại họ Vương,\n',
 'Gia tư nghĩ cũng thường thường bực trung.\n',
 'Một trai con thứ rốt lòng,\n',
 'Vương Quan là chữ, nối dòng nho gia.\n',
 'Đầu lòng hai ả tố nga,\n',
 'Thúy Kiều là chị, em là Thúy Vân.\n',
 'Mai cốt cách, tuyết tinh thần,\n',
 'Một người một vẻ, mười phân vẹn mười.\n',
 'Vân xem trang trọng khác vời,\n',
 'Khuôn trăng đầy đặn, nét ngài nỞ nang.\n',
 'Hoa cười ngọc thốt đoan trang,\n',
 'Mây thua nước tóc, tuyết nhường màu da.\n',
 'Kiều càng sắc sảo, mặn mà,\n',
 'So bề tài, sắc, lại là phần hơn.\n',
 'Làn thu thủy, nét xuân sơn,\n',
 'Hoa ghen thua thắm, liễu hờn 

## 2. Xây dựng tokenizer

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import text_to_word_sequence

In [ ]:
for i in range(len(corpus)):
  corpus[i] = text_to_word_sequence(corpus[i])

In [ ]:
corpus

[['trăm', 'năm', 'trong', 'cõi', 'người', 'ta'],
 ['chữ', 'tài', 'chữ', 'mệnh', 'khéo', 'là', 'ghét', 'nhau'],
 ['trải', 'qua', 'một', 'cuộc', 'bể', 'dâu'],
 ['những', 'điều', 'trông', 'thấy', 'mà', 'đau', 'đớn', 'lòng'],
 ['lạ', 'gì', 'bỉ', 'sắc', 'tư', 'phong'],
 ['trời', 'xanh', 'quen', 'thói', 'má', 'hồng', 'đánh', 'ghen'],
 ['cảo', 'thơm', 'lần', 'giở', 'trước', 'đèn'],
 ['phong', 'tình', 'có', 'lục', 'còn', 'truyền', 'sử', 'xanh'],
 ['rằng', 'năm', 'gia', 'tĩnh', 'triều', 'minh'],
 ['bốn', 'phương', 'phẳng', 'lặng', 'hai', 'kinh', 'vững', 'vàng'],
 ['có', 'nhà', 'viên', 'ngoại', 'họ', 'vương'],
 ['gia', 'tư', 'nghĩ', 'cũng', 'thường', 'thường', 'bực', 'trung'],
 ['một', 'trai', 'con', 'thứ', 'rốt', 'lòng'],
 ['vương', 'quan', 'là', 'chữ', 'nối', 'dòng', 'nho', 'gia'],
 ['đầu', 'lòng', 'hai', 'ả', 'tố', 'nga'],
 ['thúy', 'kiều', 'là', 'chị', 'em', 'là', 'thúy', 'vân'],
 ['mai', 'cốt', 'cách', 'tuyết', 'tinh', 'thần'],
 ['một', 'người', 'một', 'vẻ', 'mười', 'phân', 'vẹn', 'mười'],


In [ ]:
tokenizer = Tokenizer(oov_token='<OOV>')
tokenizer.fit_on_texts(corpus)
w2id = tokenizer.word_index

In [ ]:
w2id

{'<OOV>': 1,
 'một': 2,
 'lòng': 3,
 'người': 4,
 'rằng': 5,
 'là': 6,
 'hoa': 7,
 'đã': 8,
 'có': 9,
 'đâu': 10,
 'như': 11,
 'ra': 12,
 'mà': 13,
 'vàng': 14,
 'lời': 15,
 'lại': 16,
 'xuân': 17,
 'tình': 18,
 'xa': 19,
 'trong': 20,
 'thấy': 21,
 'hai': 22,
 'nhà': 23,
 'cũng': 24,
 'về': 25,
 'bóng': 26,
 'nàng': 27,
 'tiếng': 28,
 'biết': 29,
 'xanh': 30,
 'hồng': 31,
 'càng': 32,
 'hương': 33,
 'lần': 34,
 'tay': 35,
 'mới': 36,
 'nào': 37,
 'kiều': 38,
 'nước': 39,
 'tường': 40,
 'ai': 41,
 'ngày': 42,
 'đây': 43,
 'mình': 44,
 'cho': 45,
 'gió': 46,
 'đến': 47,
 'này': 48,
 'mặt': 49,
 'sinh': 50,
 'tài': 51,
 'trông': 52,
 'trời': 53,
 'còn': 54,
 'bên': 55,
 'thì': 56,
 'nghe': 57,
 'vào': 58,
 'phong': 59,
 'thanh': 60,
 'nửa': 61,
 'không': 62,
 'duyên': 63,
 'với': 64,
 'chi': 65,
 'chẳng': 66,
 'chưa': 67,
 'gì': 68,
 'trăng': 69,
 'ngoài': 70,
 'thế': 71,
 'đà': 72,
 'chút': 73,
 'chiều': 74,
 'nhớ': 75,
 'song': 76,
 'ta': 77,
 'điều': 78,
 'đầu': 79,
 'sẵn': 80,
 'cầm'

In [ ]:
from tensorflow.keras.utils import to_categorical

## 3. Xử lý dữ liệu cho CBOW

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
window_size = 2

In [ ]:
import numpy as np
def generate_pairs(window_size, corpus):
  """
  Tiến hành lấy 1 từ khỏi câu làm nhãn và sử dụng câu bao
  gồm k từ bên trái và k từ bên phải (trường hợp này window_size = k) làm đầu vào

  Đầu vào:
    window_size:
      Dạng: Python integer
      Miêu tả: k từ bên trái/phải được giữ lại
    corpus:
      Dạng: Python Dictionary
      Miêu tả: từ điển nối từ và id
  """
  X = []
  y = []
  for words in corpus:
    start = 0
    while start + window_size * 2 < len(words):
      end = start + window_size * 2
      tar_i = start + window_size

      # Lựa chọn từ ở vị trí hiện tại làm nhãn
      label = words[tar_i]

      # Nối k từ bên trái và k từ bên phải của từ này thành 1 câu
      x = [" ".join(words[start:tar_i] + words[tar_i+1:end+1])]

      print(words)
      print(x, "--->", label)
      start += 1
      X.append(tokenizer.texts_to_sequences(x)[0])
      y.append(to_categorical( tokenizer.word_index[label], len(tokenizer.word_index) + 1))

  return tf.convert_to_tensor(X) , tf.convert_to_tensor(y)

In [ ]:
X_train, y_train = generate_pairs(window_size, corpus)


['trăm', 'năm', 'trong', 'cõi', 'người', 'ta']
['trăm năm cõi người'] ---> trong
['trăm', 'năm', 'trong', 'cõi', 'người', 'ta']
['năm trong người ta'] ---> cõi
['chữ', 'tài', 'chữ', 'mệnh', 'khéo', 'là', 'ghét', 'nhau']
['chữ tài mệnh khéo'] ---> chữ
['chữ', 'tài', 'chữ', 'mệnh', 'khéo', 'là', 'ghét', 'nhau']
['tài chữ khéo là'] ---> mệnh
['chữ', 'tài', 'chữ', 'mệnh', 'khéo', 'là', 'ghét', 'nhau']
['chữ mệnh là ghét'] ---> khéo
['chữ', 'tài', 'chữ', 'mệnh', 'khéo', 'là', 'ghét', 'nhau']
['mệnh khéo ghét nhau'] ---> là
['trải', 'qua', 'một', 'cuộc', 'bể', 'dâu']
['trải qua cuộc bể'] ---> một
['trải', 'qua', 'một', 'cuộc', 'bể', 'dâu']
['qua một bể dâu'] ---> cuộc
['những', 'điều', 'trông', 'thấy', 'mà', 'đau', 'đớn', 'lòng']
['những điều thấy mà'] ---> trông
['những', 'điều', 'trông', 'thấy', 'mà', 'đau', 'đớn', 'lòng']
['điều trông mà đau'] ---> thấy
['những', 'điều', 'trông', 'thấy', 'mà', 'đau', 'đớn', 'lòng']
['trông thấy đau đớn'] ---> mà
['những', 'điều', 'trông', 'thấy', 'mà', 'đ

In [ ]:
X_train

<tf.Tensor: shape=(1507, 4), dtype=int32, numpy=
array([[ 199,  119,  600,    4],
       [ 119,   20,    4,   77],
       [ 148,   51,  149,  200],
       ...,
       [  20,  253,    9,   74],
       [ 253, 1163,   74,  511],
       [1163,    9,  511, 1164]], dtype=int32)>

## 4. Xây dựng mô hình

Mô hình CBOW bao gồm
- 1 lớp Embedding với chiều được định sẵn
- 1 lớp Dense để phóng về chiều từ điển

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Lambda
from tensorflow.keras.backend import mean


Kiểm tra mô hình

In [ ]:
embedding_size = 128
cbow = Sequential()
cbow.add(Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=window_size*2))
cbow.add(Lambda(lambda x: mean(x, axis=1), output_shape=(embedding_size,) ))
cbow.add(Dense(vocab_size, activation='softmax'))




In [ ]:
cbow.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 128)            149120    
                                                                 
 lambda (Lambda)             (None, 128)               0         
                                                                 
 dense (Dense)               (None, 1165)              150285    
                                                                 
Total params: 299,405
Trainable params: 299,405
Non-trainable params: 0
_________________________________________________________________


## 5. Tiến hành training

In [ ]:
cbow.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['acc'])
cbow.fit(X_train, y_train, epochs=30, verbose=1)

Epoch 1/30
48/48 [==============================] - 9s 58ms/step - loss: 7.0547 - acc: 0.0086
Epoch 2/30
48/48 [==============================] - 1s 11ms/step - loss: 7.0019 - acc: 0.0902
Epoch 3/30
48/48 [==============================] - 0s 10ms/step - loss: 6.9149 - acc: 0.0683
Epoch 4/30
48/48 [==============================] - 0s 7ms/step - loss: 6.7432 - acc: 0.0338
Epoch 5/30
48/48 [==============================] - 0s 4ms/step - loss: 6.5153 - acc: 0.0232
Epoch 6/30
48/48 [==============================] - 0s 4ms/step - loss: 6.2945 - acc: 0.0239
Epoch 7/30
48/48 [==============================] - 0s 5ms/step - loss: 6.1040 - acc: 0.0226
Epoch 8/30
48/48 [==============================] - 0s 7ms/step - loss: 5.9368 - acc: 0.0285
Epoch 9/30
48/48 [==============================] - 0s 4ms/step - loss: 5.7752 - acc: 0.0425
Epoch 10/30
48/48 [==============================] - 0s 4ms/step - loss: 5.6053 - acc: 0.0677
Epoch 11/30
48/48 [==============================] - 0s 4ms/step -

6. Kiểm tra sinh từ

In [ ]:
example = 'Trăm năm cõi người'
example = text_to_word_sequence(example)
example = tokenizer.texts_to_sequences([example])
example = tf.convert_to_tensor(example)
cbow.predict(example)
tokenizer.index_word[np.argmax(cbow.predict(example))]

1/1 [==============================] - 0s 27ms/step


'trong'

## 6. Hiển thị Embedding

In [ ]:
weights = cbow.get_weights()[0]

In [ ]:
weights

array([[ 7.5990185e-03,  2.4730336e-02, -2.9007085e-03, ...,
        -6.4679161e-03,  6.2787533e-03,  3.7921082e-02],
       [ 3.2300837e-03,  2.9805850e-02, -3.6912788e-02, ...,
         2.1508161e-02, -2.5477886e-02,  1.8250197e-05],
       [-1.5149704e-01, -8.2380779e-02,  5.5324459e-01, ...,
        -1.2575044e-01,  8.9185357e-01,  2.8546250e-01],
       ...,
       [ 2.5822058e-01, -2.7968338e-01,  1.9820078e-01, ...,
        -2.9764467e-01, -3.2461637e-01,  3.1100342e-01],
       [ 1.7546186e-01, -2.3975278e-01, -3.1542158e-01, ...,
        -2.0626585e-01, -3.8642687e-01,  1.7157379e-01],
       [ 4.9452052e-02, -1.9606557e-01, -2.5353080e-01, ...,
         2.9148585e-01, -2.9566008e-01, -2.4046199e-01]], dtype=float32)

In [ ]:
import pandas as pd
weights = cbow.get_weights()[0]
weights = weights[1:]
print(weights.shape)

pd.DataFrame(weights, index=list(tokenizer.index_word.values())).head()

(1164, 128)


0         1         2         3         4         5         6    \
<OOV>  0.003230  0.029806 -0.036913  0.000364  0.005872  0.042677  0.005550   
một   -0.151497 -0.082381  0.553245 -0.249071 -0.077462  0.091786 -0.611780   
lòng  -0.476478  0.571136  0.576249  0.459336  0.099817 -0.305948 -0.092679   
người -0.005049 -0.313319  0.391138  0.428091 -0.326943  0.193533 -0.207483   
rằng   0.379343 -0.209849  0.606102 -0.200337 -0.416056  0.117830  0.028680   

            7         8         9    ...       118       119       120  \
<OOV> -0.030372 -0.016401 -0.019105  ...  0.045576 -0.005967  0.012212   
một   -0.764466 -0.679431  0.402287  ...  0.417555  0.065829 -0.464943   
lòng  -0.054355  0.528509 -0.053340  ...  0.096631  0.522503  0.059526   
người -0.374916  0.587723 -0.799213  ... -0.341847  0.234027 -0.255211   
rằng   0.275391  0.627618  0.864311  ...  0.255991 -0.192569 -0.360405   

            121       122       123       124       125       126       127  
<OOV> -0.033329 -0.000055  0.017794  0.003747  0.021508 -0.025478  0.000018  
một   -0.195937 -0.480294  0.083139 -0.631046 -0.125750  0.891854  0.285462  
lòng   0.281494  0.751450  0.309532 -0.071502 -0.807272 -0.442282  0.532161  
người -0.036164 -0.116566  0.208139  0.614110  0.066376 -0.775032  0.387547  
rằng   0.588564 -0.317897  0.716519 -1.120867 -0.170527  0.164192 -0.254950  

[5 rows x 128 columns]